repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.14.11
    hooks:
      - id: ruff
        args: ["--fix"]
        files: "\\.py$"
        exclude: "^(.venv|venv|dist|build)/"
      - id: ruff-format
        files: "\\.py$"
        exclude: "^(.venv|venv|dist|build)/"

  - repo: https://github.com/psf/black
    rev: 25.12.0
    hooks:
      - id: black
        files: "\\.py$"
        exclude: "^(.venv|venv|dist|build)/"

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.19.1
    hooks:
      - id: mypy
        files: "\\.py$"
        exclude: "^(.venv|venv|dist|build)/"